# Generated by Django 3.2.3 on 2021-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cont',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
