# Generated by Django 3.2.3 on 2021-05-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cont',
        ),
    ]
